version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: dependencies
    schedule:
      interval: "weekly"
    labels:
      - "actions"

  - package-ecosystem: "npm"
    directory: "/"
    target-branch: dependencies
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "eslint"
        update-types: [ "version-update:semver-major" ]
    groups:
      dev-dependencies:
        dependency-type: "development"
      prod-dependencies:
        dependency-type: "production"
