version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: dependencies
    schedule:
      interval: "weekly"
    labels:
      - "actions"
  
  - package-ecosystem: "dependencies"
    directory: "/"
    target-branch: dependencies
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
